name: Testes Integrados de API com Newman

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - test

jobs:

  newman-test:
    steps:
      - uses: Vis-Rodrigues/workflow-template/.github/workflows/test-api-newman.yml@main
        with:
          collection: postman_collection
          environment: postman_environment_prd

      - uses: Vis-Rodrigues/workflow-template/.github/workflows/deploy-github-page.yml@main
        with:
          publish_dir: '.'