name: Deploy Github Pages

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - test

jobs:

  deploy:
  
    uses: Vis-Rodrigues/workflow-template/.github/workflows/deploy-github-page.yml@main
    with:
      publish_dir: '.'