name: Testes Integrados de API com Newman

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - test

jobs:

  newman-test:
  
    uses: Vis-Rodrigues/workflow-template/.github/workflows/test-api-newman.yml@main
